Repository Cat-aclsym/Cat-aclsym_Claw_of_the_dead, pull requests merged in 2024-01, with the labels that each got.

#58 Merge branch 'feature/readme' into develop
  README.md
Labels: feature, documentation

#60 Remove unnecessary files.
  .idea/.gitignore
  .idea/discord.xml
Labels: refactor, dev

#62 Ignore `.tmp` files created by Godot.
  .gitignore
Labels: feature, dev

#63 Add cannon test scene.
  project.godot
  scenes/bullet/i_bullet.tscn
  scenes/bullet/test_bullet.tscn
  scenes/cannon/i_cannon.tscn
  scenes/cannon/test_cannon.tscn
  scenes/cannon/test_cannon_scene.tscn
  scenes/main/main.tscn
  scripts/bullet/i_bullet.gd
  scripts/cannon/i_cannon.gd
  scripts/cannon/test_cannon_scene.gd
  scripts/enemy/line.gd
Labels: feature, dev, cannon

#64 Add enemy state, fix enemy issues.
  assets/enemies/default_zombie.png
  assets/enemies/default_zombie.png.import
  assets/enemies/zombie1.png
  scenes/enemy/default_enemy_scene.tscn
  scenes/enemy/ene213E.tmp
  scenes/enemy/ene2AF.tmp
  scenes/enemy/ene43EC.tmp
  scenes/enemy/ene5D2C.tmp
  scenes/enemy/ene70A9.tmp
  scenes/enemy/ene8952.tmp
  scenes/enemy/ene9CE4.tmp
  scenes/enemy/eneF055.tmp
  scenes/enemy/enemy_scene_test.tscn
  scripts/enemy/IEnemy.gd
  scripts/enemy/IEnemySpawner.gd
Labels: feature, enemies, dev
